// 事件总线/适配器/Agent 后端等系统契约（原 schemas.ts）已迁 domains/system/events.ts，显式导出见文末 system 段。

// 归档物实体契约（治理域，CONTRACTS-SCHEMAS 自 schemas.ts 析出）。
// 归档物标准纵切模块：只从正式 domain public API 显式导出，不保留旧根文件转发层。
export {
  ArtifactRefSchema,
  ArtifactsResponseSchema,
  buildCreateArtifactRequestSchema,
  CreateArtifactResponseSchema,
  nextArtifactVersionNo,
  UploadArtifactResponseSchema,
} from './domains/artifacts/index.js';
export type {
  ArtifactRef,
  ArtifactVersionKey,
  ArtifactsResponse,
  CreateArtifactResponse,
  UploadArtifactResponse,
} from './domains/artifacts/index.js';
export {
  CONTRACT_FIXTURE_TIME,
  agentBackendCapabilitiesFixture,
  agentBackendFixtures,
  agentBackendHealthFixture,
  agentBackendInvokeResponseFixture,
  botChannelFixtures,
  dataSourceFixtures,
  apiContractFixtures,
  artifactRefFixtures,
  bridgeMemberStateFixtures,
  gitRepoRefFixtures,
  hubEventFixtures,
  governanceScenarioFixture,
  baselineScenarioFixture,
  checklistScenarioFixture,
  inventoryScenarioFixture,
  kbScenarioFixture,
  memberKnowledgeFixtures,
  scheduleScenarioFixture,
  scheduleResourceDownFixture,
  SCENARIO_WINDOW_WEEKDAY,
  SCENARIO_WINDOW_CONVERGENCE,
  GOVERNANCE_SCENARIO_TIME,
  GOVERNANCE_SCENARIO_NOW,
  // per-module seed builder（模块化第5步·§5）：无机器人租户可只调 buildPmSeed()+buildKbSeed()
  buildPmSeed,
  buildKbSeed,
  buildLedgerSeed,
  buildArchiveSeed,
  buildGovernanceSeed,
  buildScheduleSeed,
  buildScheduleResourceDownVariant,
  // 打磨轮刀⑤：空板默认组树（GovStore.ensureDefaultGroups 消费）
  buildDefaultGroupTree,
} from './fixtures.js';
export type {
  PmSeedFixture,
  KbGrowthSeedFixture,
  LedgerAllocationRefs,
} from './fixtures.js';

// 共享基元（ActorRef / isoDateTime）+ 治理主轴域（D-028，拆 pm-core/schedule-infra 两文件）
// + 成长轴 + 派生算法 + 在场排班（D-029）+ 知识库（KB-CORE）
export * from './common.js';
// 倒排基准线标准纵切：显式导出正式 domain API；投资值对象仍由共享 investment 单源提供。
export {
  BASELINE_DRIFT_ATTACHED_DONE_THRESHOLD,
  BASELINE_DRIFT_LOOKAHEAD_WEEKS,
  BaselineAnchorsSchema,
  BaselineMilestonePublicSchema,
  BaselineMilestoneSchema,
  BaselinePhaseSchema,
  BaselinePhaseTypeSchema,
  BaselineResponseSchema,
  BaselineSegmentKindSchema,
  BaselineSegmentSchema,
  INVESTMENT_STALL_WEEKS,
  MilestoneKindSchema,
  MilestoneRobotVersionSchema,
  MilestoneStatusSchema,
  PassMilestoneRequestSchema,
  PassMilestoneResponseSchema,
  SeasonBaselinePublicSchema,
  SeasonBaselineSchema,
  TEMPLATE_NOTE_G1,
  TEMPLATE_NOTE_M1,
  TEMPLATE_NOTE_M2,
  TIME_ACCUMULATION_LABEL,
  UpdateBaselineRequestSchema,
  UpdateBaselineResponseSchema,
  deriveBaselineDrift,
  deriveGroupsBehind,
  deriveInvestmentWarnings,
  deriveRobotStageMarkers,
  deriveStagePipeline,
  deriveStageProgress,
  deriveTimeAccumulationFlags,
  generateRoboconBaselineTemplate,
  MilestoneStageSchema,
  STAGE_PIPELINE_STAGES,
} from './domains/baseline/index.js';
export type {
  BaselineAnchors,
  BaselineMilestone,
  BaselineMilestonePublic,
  BaselinePhase,
  BaselinePhaseType,
  BaselineResponse,
  BaselineSegment,
  BaselineSegmentKind,
  GroupBehindSummary,
  InvestmentWarning,
  MilestoneDrift,
  MilestoneDriftLevel,
  MilestoneKind,
  MilestoneRobotVersion,
  MilestoneStage,
  MilestoneStatus,
  PassMilestoneRequest,
  PassMilestoneResponse,
  RoboconBaselineTemplate,
  RobotStageMarker,
  SeasonBaseline,
  SeasonBaselinePublic,
  StagePipelineStage,
  StagePipelineStatus,
  StageProgress,
  TimeAccumulationFlag,
  UpdateBaselineRequest,
  UpdateBaselineResponse,
} from './domains/baseline/index.js';
// （pm-core 已迁 domains/pm/model.ts）
// 轻身份登录契约（IDENTITY-LITE，D-083 §4.2）：session / setPin，依赖 pm-core 的 MemberPublicSchema，故其后导出。
// 轻身份登录契约已迁 domains/system/identity.ts（显式导出见文件头 system 段）
// schedule 域四件套显式导出见下方 domains/schedule 段（schedule-infra 已并入 model.ts）
// （growth 已迁 domains/pm/growth.ts）
// （attribution 已迁 domains/pm/policies.ts）
// （schedule.js 已迁 domains/schedule/policies.ts）
// 知识库标准纵切模块：只从正式 domain public API 显式导出，不保留旧根文件转发层。
export {
  ARCHIVE_FILE_NAME_PATTERN,
  ArchiveDocumentSchema,
  ArchiveGeneratedBySchema,
  ERROR_CODE_PATTERN,
  ErrorEntriesResponseSchema,
  ErrorEntrySchema,
  InvestigationRecordSchema,
  InvestigationRecordTypeSchema,
  IssueCardSchema,
  IssueCardsResponseSchema,
  IssueSeveritySchema,
  IssueStatusSchema,
  KB_ARRAY_MAX,
  KB_DERIVED_PREVENTION_MAX,
  KB_ID_MAX,
  KB_LONG_TEXT_MAX,
  KB_MARKDOWN_MAX,
  KB_TAG_MAX,
  KB_TEXT_MAX,
  KB_TITLE_MAX,
  KbCloseoutRequestSchema,
  KbCloseoutResponseSchema,
  KbImportDocIssueSchema,
  KbImportDocRefSchema,
  KbImportDocsReportSchema,
  KbSimilarResponseSchema,
  SimilarIssueMatchSchema,
  buildCloseoutFromIssue,
  deriveErrorCode,
  deriveKnowledgeNodeFromIssue,
  rankSimilarIssues,
} from './domains/knowledge/index.js';
export type {
  ArchiveDocument,
  ArchiveGeneratedBy,
  CloseoutFailure,
  CloseoutGeneratedBy,
  CloseoutInput,
  CloseoutOptions,
  CloseoutResult,
  CloseoutSuccess,
  ErrorEntry,
  InvestigationRecord,
  InvestigationRecordType,
  IssueCard,
  IssueSeverity,
  IssueStatus,
  KbCloseoutRequest,
  KbCloseoutResponse,
  KbImportDocIssue,
  KbImportDocRef,
  KbImportDocsReport,
  KbSimilarResponse,
  KbSnapshot,
  RankSimilarIssuesInput,
  SimilarIssueMatch,
} from './domains/knowledge/index.js';
// 库存标准纵切模块：只从正式 domain public API 显式导出，不保留旧根文件转发层。
export {
  IDLE_HOLDER,
  INVENTORY_TEMPLATE_HEADERS,
  InventoryImportFailureSchema,
  InventoryImportReportSchema,
  InventoryImportRowSchema,
  InventoryImportRowsRequestSchema,
  InventoryLedgerPerResourceSchema,
  InventoryLedgerRowSchema,
  InventoryPreviewResponseSchema,
  InventoryResponseSchema,
  InventorySnapshotSchema,
  InvalidPartActionError,
  CreatePartActionRequestSchema,
  CreatePartActionResponseSchema,
  CreatePartTypeRequestSchema,
  CreatePartTypeResponseSchema,
  PartAcquisitionSchema,
  PartActionKindSchema,
  PartActionRecordedBySchema,
  PartActionSchema,
  PartActionSourceSchema,
  PartAllocationSchema,
  PartCategorySchema,
  PartTypeSchema,
  TrackedPartSchema,
  applyPartAction,
  buildInventoryTemplateCsv,
  deriveInventoryLedger,
  derivePartAcquisition,
  deriveShortfalls,
  parseInventoryCsv,
} from './domains/inventory/index.js';
export type {
  InventoryImportFailure,
  InventoryImportReport,
  InventoryImportRow,
  InventoryImportRowsRequest,
  InventoryLedgerPerResource,
  InventoryLedgerRow,
  InventoryParseResult,
  InventoryPreviewResponse,
  InventoryResourceRef,
  InventoryResponse,
  InventorySnapshot,
  CreatePartActionRequest,
  CreatePartActionResponse,
  CreatePartTypeRequest,
  CreatePartTypeResponse,
  PartAcquisition,
  PartAcquisitionSummary,
  PartAction,
  PartActionEffect,
  PartActionInput,
  PartActionKind,
  PartActionSource,
  PartAllocation,
  PartCategory,
  PartType,
  TrackedPart,
} from './domains/inventory/index.js';
// （gov-report 已迁 domains/pm/report.ts）
// 报账标准纵切模块：只从正式 domain public API 显式导出，不保留旧根文件转发层。
export {
  DEFAULT_REIMBURSE_PROFILE,
  CreateReimburseBatchRequestSchema,
  CreateReimburseEntryRequestSchema,
  CreateReimburseEntryResponseSchema,
  GetReimburseProfileResponseSchema,
  InvoiceRecognitionSourceSchema,
  PurchaserCheckStatusSchema,
  ReimburseAmountBucketSchema,
  ReimburseBatchResponseSchema,
  ReimburseBatchSchema,
  ReimburseBatchStatusSchema,
  ReimburseBatchSummarySchema,
  ReimburseBatchesResponseSchema,
  ReimburseEntriesResponseSchema,
  ReimburseEntryKindSchema,
  ReimburseEntrySchema,
  ReimburseEntryStatusSchema,
  ReimburseFinancialSummarySchema,
  ReimburseItemSchema,
  ReimburseMaterialsSchema,
  ReimburseProfileSchema,
  ReimburseReviewReasonSchema,
  StockInLineSchema,
  StockInContextResponseSchema,
  StockInEntryContextSchema,
  StockInPartTypeCandidateSchema,
  StockInRequestSchema,
  StockInResponseSchema,
  StockedLineSchema,
  UpdateReimburseBatchRequestSchema,
  UpdateReimburseEntryRequestSchema,
  UpdateReimburseEntryResponseSchema,
  UpdateReimburseProfileRequestSchema,
  UpdateReimburseProfileResponseSchema,
  cleanInvoiceItemName,
  classifyInvoiceEntryKind,
  deriveBatchSummary,
  derivePurchaserCheckStatus,
  deriveReimburseFinancialSummary,
  deriveReimburseReviewReasons,
  deriveReimburseStatus,
  INVOICE_ARCHIVE_LIMITS,
  isReimburseEntryBlocked,
  parseInvoicePdfText,
  parseInvoiceXbrlText,
  parseInvoiceXmlText,
  planInvoiceArchive,
  suggestReimburseFilename,
} from './domains/reimburse/index.js';
export type {
  CreateReimburseBatchRequest,
  CreateReimburseEntryRequest,
  CreateReimburseEntryResponse,
  GetReimburseProfileResponse,
  InvoiceArchiveLimits,
  InvoiceArchivePlanEntry,
  InvoiceArchiveSkipReason,
  InvoiceEntryKind,
  InvoiceRecognitionSource,
  ParsedInvoice,
  PurchaserCheckStatus,
  ReimburseAmountBucket,
  ReimburseBatch,
  ReimburseBatchResponse,
  ReimburseBatchStatus,
  ReimburseBatchSummary,
  ReimburseBatchesResponse,
  ReimburseEntriesResponse,
  ReimburseEntry,
  ReimburseEntryKind,
  ReimburseEntryStatus,
  ReimburseFinancialSummary,
  ReimburseItem,
  ReimburseMaterials,
  ReimburseProfile,
  ReimburseReviewReason,
  StockInLine,
  StockInContextResponse,
  StockInEntryContext,
  StockInPartTypeCandidate,
  StockInRequest,
  StockInResponse,
  StockedLine,
  UpdateReimburseBatchRequest,
  UpdateReimburseEntryRequest,
  UpdateReimburseEntryResponse,
  UpdateReimburseProfileRequest,
  UpdateReimburseProfileResponse,
} from './domains/reimburse/index.js';
// 门检查单标准纵切：显式导出正式 domain API；checklist 不再反向 import baseline 整域。
export {
  CHECKLIST_DRIFT_LOOKAHEAD_WEEKS,
  ChecklistDriftLevelSchema,
  ChecklistItemDriftSchema,
  ChecklistItemStatusSchema,
  ChecklistItemsResponseSchema,
  ChecklistOriginSchema,
  ChecklistQuerySchema,
  ChecklistTemplateSchema,
  ChecklistTemplatesResponseSchema,
  ClearChecklistItemRequestSchema,
  ClearChecklistItemResponseSchema,
  CreateChecklistItemRequestSchema,
  CreateChecklistItemResponseSchema,
  GateChecklistItemSchema,
  WaiveChecklistItemRequestSchema,
  WaiveChecklistItemResponseSchema,
  deriveChecklistDrift,
  listBlockingChecklistItems,
} from './domains/checklist/index.js';
export type {
  ChecklistDriftLevel,
  ChecklistItemDrift,
  ChecklistItemStatus,
  ChecklistItemsResponse,
  ChecklistOrigin,
  ChecklistQuery,
  ChecklistTemplate,
  ChecklistTemplatesResponse,
  ClearChecklistItemRequest,
  ClearChecklistItemResponse,
  CreateChecklistItemRequest,
  CreateChecklistItemResponse,
  GateChecklistItem,
  WaiveChecklistItemRequest,
  WaiveChecklistItemResponse,
} from './domains/checklist/index.js';
// 跨端单一源（D-052 重复真相收口）：系统状态契约 / PM 写请求契约（errorCode 派生已并入 kb-closeout.ts）
// （system-status 已迁 domains/system/status.ts）
// SQLite app_settings + setup 端点契约：显式列出公共 API，禁止旧 DeployConfig 兼容出口回流。
// （app-settings 已迁 domains/system/settings.ts，显式导出见文末 system 段）
// （pm-requests 已迁 domains/pm/requests.ts）
// （schedule-requests/resource-requests 已并 domains/schedule/requests.ts）
// 名册导入（ROSTER-IMPORT，K8）：CSV 模板生成 + 编码探测 + 手写零依赖解析器 + 导入报告契约（纯，无状态）。
// （roster-import 已迁 domains/pm/import.ts）
export { decodeRosterBytes } from './domains/pm/index.js';
// pm 域（治理主轴：任务/依赖/需求/知识节点/组/成员/赛季 + 快照归因 + 成长轴 + 汇报 + 名册导入）：
// 显式导出正式 domain API；investment 已并入 model.ts。
export {
  BIG_TASK_GATE_LOOKAHEAD_WEEKS,
  BlockAttributionReasonSchema,
  BlockAttributionSchema,
  BlockAttributionsResponseSchema,
  CONVERGENCE_SCOPE_ALL_LEAF_GROUPS,
  CONVERGENCE_SENTINEL_GROUP_ID,
  CreateGroupRequestSchema,
  CreateSeasonRequestSchema,
  CreateSeasonResponseSchema,
  DepEdgeKindSchema,
  DepEdgeSchema,
  DepGraphSchema,
  DepGraphSummarySchema,
  DepNodeKnowledgeSchema,
  DepNodeSchema,
  DepNodeStatusSchema,
  DependenciesResponseSchema,
  DependencySchema,
  DependencySourceSchema,
  DependencyStatusSchema,
  DependencyTypeSchema,
  DirectionGapSchema,
  DirectionGapSeveritySchema,
  GovActorSourceSchema,
  GroupGapsResponseSchema,
  GroupKindSchema,
  GroupResponseSchema,
  GroupSchema,
  GroupsResponseSchema,
  InvestmentHorizonSchema,
  InvestmentTimeAccumulationSchema,
  InvestmentValueSchema,
  MemberGradeSchema,
  MemberObjectSchema,
  MemberPublicSchema,
  MemberRoleSchema,
  MemberSchema,
  MemberStatusSchema,
  MembersResponseSchema,
  NeedSchema,
  NeedStatusSchema,
  NeedsResponseSchema,
  OverloadSignalSchema,
  ProgressSignalKindSchema,
  ProjectSchema,
  ProjectsResponseSchema,
  RenameGroupRequestSchema,
  RobotTargetSchema,
  SeasonSchema,
  SeasonsResponseSchema,
  SetGateReviewerRequestSchema,
  SetGateReviewerResponseSchema,
  SetMemberRoleRequestSchema,
  SetMemberRoleResponseSchema,
  SetProjectManagerRequestSchema,
  SetProjectManagerResponseSchema,
  TaskComplexitySchema,
  TaskInvestmentSchema,
  TaskProgressSignalSchema,
  TaskSchema,
  TaskStatusSchema,
  TaskWithMetaSchema,
  TasksQuerySchema,
  TasksResponseSchema,
  deriveMyVehicleProgress,
  deriveSeasonTaskProgress,
  deriveTaskAcceptance,
  isBigTask,
  isPostedTask,
  KnowledgeNodeSchema,
  KnowledgeNodesResponseSchema,
  MemberAvailabilitySchema,
  MemberAvailabilityVisibilitySchema,
  MemberKnowledgeRelationSchema,
  MemberKnowledgeSchema,
  MemberKnowledgeVisibilitySchema,
  TaskKnowledgeTagSchema,
  TaskKnowledgeTagsResponseSchema,
  GOVERNANCE_SNAPSHOT_ARRAY_KEYS,
  GovernanceSnapshotSchema,
  deriveBlockAttributions,
  deriveDirectionGaps,
  lookupMemberByDisplayName,
  toDepGraphView,
  wouldCreateCycle,
  AssignTaskRequestSchema,
  AssignTaskResponseSchema,
  ClaimTaskRequestSchema,
  ClaimTaskResponseSchema,
  CompleteTaskRequestSchema,
  CompleteTaskResponseSchema,
  ConfirmCrossClaimRequestSchema,
  ConfirmCrossClaimResponseSchema,
  CreateDependencyRequestSchema,
  CreateDependencyResponseSchema,
  CreateNeedRequestSchema,
  CreateNeedResponseSchema,
  CreateTaskRequestSchema,
  CreateTaskResponseSchema,
  ReviewTaskRequestSchema,
  ReviewTaskResponseSchema,
  SetTaskPartnerRequestSchema,
  SetTaskPartnerResponseSchema,
  TransitionTaskStatusRequestSchema,
  TransitionTaskStatusResponseSchema,
  WaiveDependencyResponseSchema,
  GOV_REPORT_STAGE_LABELS,
  GOV_REPORT_STAGE_STATUS_LABELS,
  GOV_REPORT_TASK_STATUS_LABELS,
  buildGovReport,
  renderGovReportHtml,
  renderGovReportMarkdown,
  GATE_REVIEWER_DEFAULT_GRADES,
  ROSTER_TEMPLATE_HEADERS,
  RosterImportFailureSchema,
  RosterImportReportSchema,
  RosterImportRowSchema,
  RosterImportRowsRequestSchema,
  RosterPreviewResponseSchema,
  buildRosterTemplateCsv,
  parseRosterCsv,
} from './domains/pm/index.js';
export type {
  BlockAttribution,
  BlockAttributionReason,
  CreateGroupRequest,
  CreateSeasonRequest,
  DepEdge,
  DepEdgeKind,
  DepGraph,
  DepGraphSummary,
  DepNode,
  DepNodeKnowledge,
  DepNodeStatus,
  Dependency,
  DependencySource,
  DependencyStatus,
  DependencyType,
  DirectionGap,
  DirectionGapSeverity,
  GovActorSource,
  Group,
  GroupGapsResponse,
  GroupKind,
  GroupResponse,
  GroupsResponse,
  InvestmentHorizon,
  InvestmentTimeAccumulation,
  InvestmentValue,
  Member,
  MemberGrade,
  MemberPublic,
  MemberRole,
  MemberStatus,
  MyVehicleProgress,
  Need,
  NeedStatus,
  OverloadSignal,
  ProgressSignalKind,
  Project,
  RenameGroupRequest,
  RobotTarget,
  Season,
  SetGateReviewerRequest,
  SetGateReviewerResponse,
  SetMemberRoleRequest,
  SetMemberRoleResponse,
  SetProjectManagerRequest,
  SetProjectManagerResponse,
  Task,
  TaskAcceptanceState,
  TaskComplexity,
  TaskConvergenceScope,
  TaskInvestment,
  TaskProgress,
  TaskProgressSignal,
  TaskStatus,
  TaskWithMeta,
  TasksQuery,
  KnowledgeNode,
  MemberAvailability,
  MemberAvailabilityVisibility,
  MemberKnowledge,
  MemberKnowledgeRelation,
  MemberKnowledgeVisibility,
  TaskKnowledgeTag,
  GovernanceSnapshot,
  DisplayNameLookup,
  AssignTaskRequest,
  AssignTaskResponse,
  ClaimTaskRequest,
  ClaimTaskResponse,
  CompleteTaskRequest,
  CompleteTaskResponse,
  ConfirmCrossClaimRequest,
  ConfirmCrossClaimResponse,
  CreateDependencyRequest,
  CreateDependencyResponse,
  CreateNeedRequest,
  CreateNeedResponse,
  CreateTaskRequest,
  CreateTaskResponse,
  ReviewTaskRequest,
  ReviewTaskResponse,
  SetTaskPartnerRequest,
  SetTaskPartnerResponse,
  TransitionTaskStatusRequest,
  TransitionTaskStatusResponse,
  WaiveDependencyResponse,
  GovReport,
  GovReportGroupCount,
  GovReportInput,
  GovReportMilestoneRow,
  RosterImportFailure,
  RosterImportReport,
  RosterImportRow,
  RosterImportRowsRequest,
  RosterParseResult,
  RosterPreviewResponse,
} from './domains/pm/index.js';
// 车队批量导入（FLEET-CSV-IMPORT）：CSV 模板生成 + 手写零依赖解析器 + 预览契约（纯，无状态；落库走既有批量端点）。
// （fleet-import 已迁 domains/schedule/import.ts）
// 在场排班/接力标准纵切模块（含资源车 + 车队 CSV 导入）：只从正式 domain public API 显式导出。
export {
  canBoardResource,
  DefaultPresetSchema,
  PresenceFeasibilitySchema,
  PresenceModeSchema,
  PresenceReasonSchema,
  PresenceRecommendationSchema,
  PresenceScheduleResponseSchema,
  RelayHandoffSchema,
  ResourceKindSchema,
  ResourceSessionSchema,
  ResourceSessionsResponseSchema,
  ResourceStatusSchema,
  SharedResourceSchema,
  SharedResourcesResponseSchema,
  WeeklyMinuteWindowSchema,
  WindowDefSchema,
  deriveGroupAvailability,
  deriveLeafGroups,
  derivePresenceSchedule,
  deriveRelayBoard,
  deriveTodayPlanFromPresets,
  RelayBoardResponseSchema,
  RelayStageSchema,
  CreateRelayHandoffRequestSchema,
  CreateResourceRequestSchema,
  CreateResourceResponseSchema,
  CreateResourceSessionRequestSchema,
  CreateResourceSessionResponseSchema,
  CreateResourceSessionsBatchRequestSchema,
  CreateResourceSessionsBatchResponseSchema,
  CreateResourcesBatchRequestSchema,
  CreateResourcesBatchResponseSchema,
  RelayHandoffResponseSchema,
  RESOURCE_INIT_STATUSES,
  UpdateResourceDefaultPresetRequestSchema,
  UpdateResourceDefaultPresetResponseSchema,
  UpdateResourceResponseSchema,
  UpdateResourceSessionRequestSchema,
  UpdateResourceSessionResponseSchema,
  UpdateResourceStatusRequestSchema,
  buildFleetTemplateCsv,
  FLEET_TEMPLATE_HEADERS,
  FleetImportFailureSchema,
  FleetImportRowSchema,
  FleetPreviewResponseSchema,
  parseFleetCsv,
} from './domains/schedule/index.js';
export type {
  DefaultPreset,
  PresenceFeasibility,
  PresenceMode,
  PresenceReason,
  PresenceRecommendation,
  PresenceScheduleResponse,
  RelayHandoff,
  ResourceKind,
  ResourceSession,
  ResourceSessionsResponse,
  ResourceStatus,
  SharedResource,
  SharedResourcesResponse,
  WeeklyMinuteWindow,
  WindowDef,
  AvailabilityContext,
  RelayBoard,
  RelayBoardResponse,
  RelayStage,
  ScheduleSnapshot,
  TodayPlanSessionDraft,
  CreateRelayHandoffRequest,
  CreateResourceRequest,
  CreateResourceResponse,
  CreateResourceSessionRequest,
  CreateResourceSessionResponse,
  CreateResourceSessionsBatchRequest,
  CreateResourceSessionsBatchResponse,
  CreateResourcesBatchRequest,
  CreateResourcesBatchResponse,
  RelayHandoffResponse,
  UpdateResourceDefaultPresetRequest,
  UpdateResourceDefaultPresetResponse,
  UpdateResourceResponse,
  UpdateResourceSessionRequest,
  UpdateResourceSessionResponse,
  UpdateResourceStatusRequest,
  FleetImportFailure,
  FleetImportRow,
  FleetParseResult,
  FleetPreviewResponse,
} from './domains/schedule/index.js';
export * from './csv-core.js';
// 装配契约（HUB-MODULARIZATION 第2步）：ModuleDescriptor / TenantConfig / VocabularyRegistry，只接口不实现。
// （assembly 已迁 domains/system/assembly.ts）
// robotics 垂直包（HUB-MODULARIZATION 第6步）：词汇 + 词汇相关派生函数，只此一个已注册垂直包。
export * from './verticals/robotics.js';
// Hermes 入站命令契约（HUB-HERMES-ADAPTER 最小链路）：命令枚举 + 参数 schema + 原始文本规则匹配（纯，无 I/O）。
// （hermes 已迁 domains/integrations/hermes.ts）
// 飞书集成配置（LARK-INTEG-CONFIG）：配置 CRUD 契约 + Hermes credential 端点契约。
// （lark-integration 已迁 domains/integrations/lark.ts）

// system 域（身份/设置/状态/装配/事件总线契约）：显式导出正式 domain API。
export {
  ClearPinResponseSchema,
  IdentityModeSchema,
  SessionIdentitySchema,
  SessionRequestSchema,
  SessionResponseSchema,
  SetPinRequestSchema,
  SetPinResponseSchema,
  SetupSuperAdminRequestSchema,
  SetupSuperAdminResponseSchema,
  AppSettingsSchema,
  ConfigIdentityModeSchema,
  DataModeSchema,
  SetupConfigRequestSchema,
  SetupConfigResponseSchema,
  SetupGraduateResponseSchema,
  SetupInitRequestSchema,
  SetupInitResponseSchema,
  SetupStateResponseSchema,
  VerticalIdSchema,
  parseAppSettings,
  DeploymentInfoSchema,
  DeploymentStorageEntrySchema,
  HealthResponseSchema,
  SystemStatusResponseSchema,
  ALL_MODULE_IDS,
  EnabledModulesSchema,
  ModuleIdSchema,
  ROBOTICS_TENANT_CONFIG,
  TenantConfigSchema,
  isModuleEnabled,
  AdapterCapabilitiesResponseSchema,
  AdapterDescriptorSchema,
  AdapterHealthResponseSchema,
  AdapterInvokeRequestSchema,
  AdapterInvokeResponseSchema,
  AdaptersResponseSchema,
  AgentBackendCapabilitiesResponseSchema,
  AgentBackendHealthResponseSchema,
  AgentBackendInvokeRequestSchema,
  AgentBackendInvokeResponseSchema,
  AgentBackendSchema,
  AgentBackendsResponseSchema,
  BotChannelSchema,
  BotChannelsResponseSchema,
  BridgeMemberStateSchema,
  BridgeMembersResponseSchema,
  DataSourceSchema,
  DataSourcesResponseSchema,
  ErrorResponseSchema,
  GitRepoRefSchema,
  GitReposResponseSchema,
  HubEventSchema,
  HubEventSourceSchema,
  HubEventTypeSchema,
  HubEventsResponseSchema,
} from './domains/system/index.js';
export type {
  ClearPinResponse,
  IdentityMode,
  SessionIdentity,
  SessionRequest,
  SessionResponse,
  SetPinRequest,
  SetPinResponse,
  SetupSuperAdminRequest,
  SetupSuperAdminResponse,
  AppSettings,
  ConfigIdentityMode,
  DataMode,
  SetupConfigRequest,
  SetupConfigResponse,
  SetupGraduateResponse,
  SetupInitRequest,
  SetupInitResponse,
  SetupStateResponse,
  VerticalId,
  DeploymentInfo,
  DeploymentStorageEntry,
  HealthResponse,
  SystemStatusResponse,
  ModuleDescriptor,
  ModuleI18nBundle,
  ModuleId,
  ModuleNavItem,
  ModulePageDescriptor,
  TenantConfig,
  VocabularyRegistry,
  AdapterCapabilitiesResponse,
  AdapterDescriptor,
  AdapterHealthResponse,
  AdapterInvokeRequest,
  AdapterInvokeResponse,
  AdaptersResponse,
  AgentBackend,
  AgentBackendCapabilitiesResponse,
  AgentBackendHealthResponse,
  AgentBackendInvokeRequest,
  AgentBackendInvokeResponse,
  AgentBackendsResponse,
  BotChannel,
  BotChannelsResponse,
  BridgeMemberState,
  BridgeMembersResponse,
  DataSource,
  DataSourcesResponse,
  ErrorResponse,
  GitRepoRef,
  GitReposResponse,
  HubEvent,
  HubEventSource,
  HubEventType,
  HubEventsResponse,
} from './domains/system/index.js';

// integrations 域（Hermes 入站命令 / 飞书集成配置）：显式导出正式 domain API。
export {
  HermesCommandSchema,
  HermesInboundRequestSchema,
  HermesInboundResponseSchema,
  HermesInvQueryArgsSchema,
  HermesInvRecordActionSchema,
  HermesInvRecordArgsSchema,
  HermesStructuredRequestSchema,
  HermesTextRequestSchema,
  parseHermesText,
  HermesCredentialResponseSchema,
  LarkChatSchema,
  LarkChatsResponseSchema,
  LarkConfigResponseSchema,
  LarkConfigSaveRequestSchema,
  LarkConfigSaveResponseSchema,
  LarkConfigSchema,
  LarkCreateChatRequestSchema,
  LarkCreateChatResponseSchema,
  LarkPushReminderResponseSchema,
} from './domains/integrations/index.js';
export type {
  HermesCommand,
  HermesInboundRequest,
  HermesInboundResponse,
  HermesInvQueryArgs,
  HermesInvRecordAction,
  HermesInvRecordArgs,
  HermesParseResult,
  HermesCredentialResponse,
  LarkChat,
  LarkChatsResponse,
  LarkConfig,
  LarkConfigResponse,
  LarkConfigSaveRequest,
  LarkConfigSaveResponse,
  LarkCreateChatRequest,
  LarkCreateChatResponse,
  LarkPushReminderResponse,
} from './domains/integrations/index.js';
